HOST: http://aaaaaaaaa.apiary.io

--- Moje nove API v2 ---
---
Welcome to the ddddddsssssssss API documentation. All comments can be written in (support [Markdown](http://daringfirebalsssssssaaasl.net/projects/markdown/syntax) syntax)
---

--
Shopping Cart Resources
The following is a section of resources related to the shopping cart
--
List products added into your shopping-cart. (comment block again in Markdown)
GET /shopping-cart
< 200
< Content-Type: application/json
{ "items": [
  { "url": "/shopping-cart/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }

List products added into your shop-list
GET /shop-list
< 200
< Content-Type: text/xml
<items>
  <product>2ZY48XPZaaaa</product><quantity>1</quantity><name>New socks</name><price>1.25</price>
</items>

List products added into your shop-list
GET /shop
< 200
< Content-Type: text/xml
<items>
  <product>Pokus2ZY48XPZ</product><quantity>1</quantity><name>New socks</name><price>1.25</price>
</items>

Save new products in your shopping cart
POST /shopping-cart
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }


--
Payment Resources 
The following is a section of resources related to the payment
--
This resource allows you to submit payment information to process your *shopping cart* items
POST /payment
{ "cc"": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }