HOST: http://api.apiary.io/

--- Apiary.io ---
---
Apiary loves API. Of course then, we have API too. 
---
-- Blueprint --

Send an existing blueprint and return generated HTML. Both are expected to be in UTF-8
POST /blueprint/generate
> Accept: text/html
> Content-Type: text/plain
--- Apiary.io ---
---
Apiary loves API. Of course then, we have API too.         
---
-- Blueprint --
< 200
< Content-Type: text/html
<div id="documentationCointainer">
  <div id="leftColumn">
    <h1 id="apiHeadline">Apiary.io</h1>
    <div class="details"><p>Apiary loves API. Of course then, we have API too. </p></div>
    <a name="blueprint"></a>
    <div class="chapterWrapper">
    <hgroup class="chapter">
      <h1>Blueprint</h1>
    </hgroup>
    </div>
  </div>
</div>



